[Variables]
Background_Width=250
Background_Height=250
Background_Color=0,0,0
Background_Opacity=0
Background_Corner_Round=12
Round_Rectangle_Shape_Color=244,219,241
Current_Condition_And_Weather_Icon_Background_Color=235,181,237
Feels_And_Low_Tonight_Temperature_Shape_Background_Color=246,184,174
Current_Temperature_Shape_Stroke_Color=31,72,118
;Font Styles
Font_Color=31,72,118
Font_Face=SF Pro Display
Font_Weight=500
;Current Weather Condition Icon Dimensions
Current_Weather_Condition_W=60
Current_Weather_Condition_H=60