[Variables]
Background_Width=400
Background_Height=400
Background_Color=32, 32, 32
Background_Opacity=200
Background_Corner_Round=12
Round_Rectangle_Shape_Color=48,48,56
Weather_Icon_Ellipse_Shape_Color=64,64,70
;Font Styles
Font_Color=255, 255, 255
Font_Face=SF Pro Display
Font_Weight=300
;Current Weather Condition Icon Dimensions
Current_Weather_Condition_W=100
Current_Weather_Condition_H=100

Daily_And_Hourly_Forecast_Toggle_Shape_Color=120,120,120
Daily_And_Hourly_Forecast_Toggle_Shape_Accent_Color=43,77,139
Data_Forecast_Shape_Color=43,77,139