[Variables]
Background_Width=400
Background_Height=400
Background_Color=32, 32, 32
Background_Opacity=200
Background_Corner_Round=12
;Font Styles
Font_Color=255, 255, 255
Font_Face=SF Pro Display
Font_Weight=300
;Current Weather Condition Icon Dimensions
Current_Weather_Condition_W=100
Current_Weather_Condition_H=100
Data_Forecast_Shape_Y=235
Data_Forecast_Shape_W=65
Data_Forecast_Shape_H=150
Data_Forecast_Weather_Icon_W=50
Data_Forecast_Weather_Icon_H=50
Sub_Content_Color=120,120,120
Accent_Color=43,77,139
